#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

var=1
while [ $var -le 100 ]
do
	if [[ $((var % 3)) -eq 0 && $((var % 5)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [ $((var % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((var % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo $var
	fi
	var=$((var + 1))
done
