#!/usr/bin/env bash
# Write a Bash script that displays the content of the file

if [ -f /etc/passwd ]
then
	while IFS= read -r line
	do
		echo "$line" >> read_cut
	done < /etc/passwd
fi
cut -d ":" -f 1,3,6 read_cut
