#!/usr/bin/env bash
# to get Apache to run on the container and to return a page
# containing Hello Holberton when querying the root of it.
echo "ServerName localhost" >> /etc/apache2/apache2.conf
echo "Hello Holberton" > /var/www/html/index.html
service apache2 start
