#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 54.84.23.55
    HostName 54.84.23.55
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
